version: '3.7'
services:
  
  spamassassin-app:
    image: registry.selfdesign.org/docker/spamassassin
    container_name: spamassassin-app
    ports: 
    - 783:783
    volumes:
    - ./logs/spamassassin:/var/log/spamassassin
    - ./conf:/etc/mail/spamassassin
    - ./data:/var/lib/spamassassin
    environment:
    - ZABBIX_HOSTNAME=spamassassin-app
    networks:
    - internal
    - services
    restart: always

networks:
  internal:
    external: false
  services:
    external: true


